development:
  adapter: postgresql
  database: prelaunchr_dev
  host: localhost
  username: postgres
  password:

test:
  adapter: postgresql
  database: prelaunchr_test
  host: localhost
  username: postgres
  password:

production:
  adapter: postgresql
  database: prelaunchr_prod
  host: localhost
  username: postgres
  password:
